name: Check Code Format

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  check_code_format:
    runs-on: ubuntu-latest
    # steps:
    #   #using: "composite"
    #   - uses: actions/checkout@v2

    #   - id: check
    #     uses: ArthurBandaryk/dev-tools@main
    #using: "composite"
    steps:
        - uses: actions/checkout@v2

        - name: Initialize and update submodule
          run: git submodule update --init

        - id: check
          uses: ArthurBandaryk/dev-tools@main
